template_path: src/vpc.py


parameters:
  Project: WordpressEFS
  Environment: prod
  VpcCidr: 10.1.0.0/16
  PublicSubnet1: 10.1.10.0/24
  PublicSubnet2: 10.1.20.0/24
  PrivateSubnet1: 10.1.11.0/24
  PrivateSubnet2: 10.1.21.0/24
  AvailabilityZone1: us-east-1a
  AvailabilityZone2: us-east-1b
